### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by AlexanderSiguenza** [Kallahans21/programming_project-#2]
Buen trabajo el que realizaron felicidades, en la entrega FINAL del proyecto, código organizado, limpio, bien documentado el archivo README, sus actividades organizadas en Trello y buena estructura y creatividad en el manual de usuario.

Ya se lo había mencionado en la segunda entrega.  Pero era necesario hacerlo nuevamente, "BUEN TRABAJO"

**Comment by AlexanderSiguenza** [comment]
Excelente trabajo , de las mejores narraciones , para la defensa del proyecto.

**Comment by Cartagena2001** [comment]
Hola
